module.exports = function(grunt) {

    grunt.initConfig({
        watch: {
            files: ['bookmarklet/**/*.js', 'lib/**/*.js', 'lib/**/*.css'],
            tasks: ['compile-bookmarklet']
        }
    });

    grunt.loadNpmTasks('grunt-contrib-watch');

    grunt.registerTask('compile-bookmarklet', function(){
        function fileToString(filepath){
            var fileContents = grunt.file.read(filepath);
            fileContents = fileContents.replace(/\\/g,'\\\\').replace(/\n/g, '\\n').replace(/\'/g, '\\\'').replace(/\"/g, '\\\"');
            return fileContents;
        }

        var generalCss = fileToString('lib/overlay-page-css.css');
        var generalJs = fileToString('lib/overlay-page-js.js');

        var header = '// Generated by gruntfile based on bookmarklet directory'
        var bookmarkletJs = header + '\n' + grunt.file.read('bookmarklet/bookmarklet-code.js');

        bookmarkletJs = bookmarkletJs.replace('{{generalCss}}', generalCss);
        bookmarkletJs = bookmarkletJs.replace('{{generalJs}}', generalJs);

        grunt.file.write('bookmarklet.js', bookmarkletJs)

    })

};
